<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.ActivityMonitor.SimpleSender" Version="26.0.2" />
    <PackageReference Include="CK.PerfectEvent" Version="27.0.2" />
    <PackageReference Include="System.IO.Pipelines" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.IO.CommChannel\CK.IO.CommChannel.csproj" />
  </ItemGroup>
</Project>